import Head from "next/head";
import { Profile } from "@/components/Profile";
import { TxReceiptList } from "@/components/TxReceiptList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-[800px] mt-12 mx-auto">
        <Profile />
        <h2 className="font-bold text-2xl mt-6 mb-2">Transaction recipts</h2>
        <TxReceiptList />
      </main>
    </>
  );
}
